#!/bin/bash
python setup.py develop

sh db/scripts/setup_db

if [ ! -d "clusterflunk/static/css" ]; then
    mkdir clusterflunk/static/css
fi
sass clusterflunk/static/scss/bootstrap.scss:clusterflunk/static/css/bootstrap.css