#!/bin/bash
python setup.py develop
sh db/scripts/setup_db

git submodule init
git submodule update

mkdir clusterflunk/static/slicknasty/css
sass clusterflunk/static/slicknasty/scss/bootstrap.scss:clusterflunk/static/slicknasty/css/bootstrap.css
mkdir clusterflunk/static/css
sass clusterflunk/static/scss/bootstrap.scss:clusterflunk/static/css/bootstrap.css