"""Forgot to delete the post field on Post.

Revision ID: 10614c943adf
Revises: 10061b77aa2a
Create Date: 2012-06-17 06:00:03.629779

"""

# downgrade revision identifier, used by Alembic.
revision = '10614c943adf'
down_revision = '10061b77aa2a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', u'score')
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column(u'score', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
