"""Added a 'created' column on the Post model.

Revision ID: 10c000a858f2
Revises: bb7f792d8f2
Create Date: 2012-03-12 23:42:33.610541

"""

# downgrade revision identifier, used by Alembic.
down_revision = 'bb7f792d8f2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('created', sa.DateTime(), nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'created')
    ### end Alembic commands ###
