"""Added a 'created' field to the Comment model.

Revision ID: 1b1341dc03f3
Revises: 4fc60ee0d0f0
Create Date: 2012-06-03 12:19:30.666907

"""

# downgrade revision identifier, used by Alembic.
revision = '1b1341dc03f3'
down_revision = '4fc60ee0d0f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created', sa.DateTime(), nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'created')
    ### end Alembic commands ###
