"""Added a StatusComment model to facilitate commenting upon statuses.

Revision ID: 1e508c63d41a
Revises: 52f609d6bdcb
Create Date: 2012-04-27 19:33:54.147615

"""

# downgrade revision identifier, used by Alembic.
revision = '1e508c63d41a'
down_revision = '52f609d6bdcb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_comments')
    ### end Alembic commands ###
