"""Added the new broadcasts table to link StudyGroup and Status

Revision ID: 250fc8c12ecc
Revises: 472bf4e7b765
Create Date: 2012-04-09 22:20:59.371204

"""

# downgrade revision identifier, used by Alembic.
down_revision = '472bf4e7b765'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcasts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('status_id', sa.Integer(), nullable=True),
        sa.Column('study_group_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
        sa.ForeignKeyConstraint(['study_group_id'], ['study_groups.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('broadcasts')
    ### end Alembic commands ###
