"""Added a description to the StudyGroup model.

Revision ID: 2862818dc0ab
Revises: 250fc8c12ecc
Create Date: 2012-04-21 14:56:11.959599

"""

# downgrade revision identifier, used by Alembic.
down_revision = '250fc8c12ecc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_groups', sa.Column('description', sa.String(length=500), nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_groups', 'description')
    ### end Alembic commands ###
