"""Added a 'title' column to the Post model.

Revision ID: 44356600fc43
Revises: 10c000a858f2
Create Date: 2012-03-13 00:44:00.302829

"""

# downgrade revision identifier, used by Alembic.
down_revision = '10c000a858f2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(length=100), nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    ### end Alembic commands ###
