"""Added a 'title' field to the ArticleHistory model.

Revision ID: 472bf4e7b765
Revises: 318fec9713f7
Create Date: 2012-03-13 13:30:40.367952

"""

# downgrade revision identifier, used by Alembic.
down_revision = '318fec9713f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_history', sa.Column('title', sa.String(length=100), nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_history', 'title')
    ### end Alembic commands ###
