"""Forgot to delete one of the fields on the Status model that got moved to the StatusHistory model.

Revision ID: 4fc60ee0d0f0
Revises: 42a5ec03e952
Create Date: 2012-06-02 23:44:50.922529

"""

# downgrade revision identifier, used by Alembic.
revision = '4fc60ee0d0f0'
down_revision = '42a5ec03e952'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statuses', u'body')
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column(u'body', sa.VARCHAR(length=1000), nullable=True))
    ### end Alembic commands ###
