"""Deleted the title field on the Post model.

Revision ID: 54ad01e8de85
Revises: 1b1341dc03f3
Create Date: 2012-06-03 21:53:04.426674

"""

# downgrade revision identifier, used by Alembic.
revision = '54ad01e8de85'
down_revision = '1b1341dc03f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', u'title')
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column(u'title', sa.VARCHAR(length=100), nullable=True))
    ### end Alembic commands ###
