"""Initial schema.

Revision ID: 5a9e360f7378
Revises: None
Create Date: 2012-03-10 17:17:44.951503

"""

# downgrade revision identifier, used by Alembic.
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=True),
        sa.Column('email', sa.String(length=50), nullable=True),
        sa.Column('joined', sa.DateTime(), nullable=True),
        sa.Column('last_online', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('networks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.Column('edited', sa.DateTime(), nullable=True),
        sa.Column('network_id', sa.Integer(), nullable=True),
        sa.Column('founder_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['founder_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('founder_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['founder_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('founder_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['founder_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moderators',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('study_group_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['study_group_id'], ['study_groups.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('study_group_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['study_group_id'], ['study_groups.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=True),
        sa.Column('password', sa.String(length=80), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statuses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.Column('body', sa.String(length=1000), nullable=True),
        sa.Column('author_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('study_group_id', sa.Integer(), nullable=True),
        sa.Column('founder_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['founder_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['study_group_id'], ['study_groups.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_comments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=True),
        sa.Column('comment_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
        sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('revision', sa.Integer(), nullable=True),
        sa.Column('author_id', sa.Integer(), nullable=True),
        sa.Column('post_id', sa.Integer(), nullable=True),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('description', sa.String(length=1000), nullable=True),
        sa.Column('due', sa.DateTime(), nullable=True),
        sa.Column('active', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('revision', sa.Integer(), nullable=True),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.Column('author_id', sa.Integer(), nullable=True),
        sa.Column('comment_id', sa.Integer(), nullable=True),
        sa.Column('body', sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('revision', sa.Integer(), nullable=True),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.Column('author_id', sa.Integer(), nullable=True),
        sa.Column('article_id', sa.Integer(), nullable=True),
        sa.Column('body', sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=True),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_users_groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('auth_user_id', sa.Integer(), nullable=True),
        sa.Column('auth_group_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['auth_group_id'], ['auth_groups.id'], ),
        sa.ForeignKeyConstraint(['auth_user_id'], ['auth_users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_comments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('article_id', sa.Integer(), nullable=True),
        sa.Column('comment_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
        sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_comments')
    op.drop_table('auth_users_groups')
    op.drop_table('post_categories')
    op.drop_table('categories')
    op.drop_table('article_history')
    op.drop_table('auth_groups')
    op.drop_table('comment_history')
    op.drop_table('post_history')
    op.drop_table('post_comments')
    op.drop_table('posts')
    op.drop_table('statuses')
    op.drop_table('auth_users')
    op.drop_table('subscriptions')
    op.drop_table('moderators')
    op.drop_table('articles')
    op.drop_table('comments')
    op.drop_table('study_groups')
    op.drop_table('networks')   
    op.drop_table('users')
    ### end Alembic commands ###
